# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccdf9b5d9b79e0509729fdb949dc719c"
name = "amazing-app"
application_url = "https://costume-sells-landing-td.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-298e71bd.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://costume-sells-landing-td.trycloudflare.com/auth/callback",
  "https://costume-sells-landing-td.trycloudflare.com/auth/shopify/callback",
  "https://costume-sells-landing-td.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
